#include "../../src/PluginInterface.h"
#include <windows.h>
#include <tchar.h>
#include <richedit.h>
#include <vector>
#include <string>
#include <algorithm>
#include "resource.h"

HINSTANCE g_hInst = NULL;

struct EmojiData {
    const wchar_t* emoji;
    const wchar_t* name;
    const wchar_t* keywords;
};

// A small subset of emojis for demonstration. In a real app, this would be much larger.
std::vector<EmojiData> g_EmojiList = {
    { L"😀", L"Grinning Face", L"smile happy face" },
    { L"😃", L"Grinning Face with Big Eyes", L"smile happy face" },
    { L"😄", L"Grinning Face with Smiling Eyes", L"smile happy face" },
    { L"😁", L"Beaming Face with Smiling Eyes", L"smile happy face" },
    { L"😆", L"Grinning Squinting Face", L"smile happy face laugh" },
    { L"😅", L"Grinning Face with Sweat", L"smile happy face sweat" },
    { L"🤣", L"Rolling on the Floor Laughing", L"smile happy face laugh rofl" },
    { L"😂", L"Face with Tears of Joy", L"smile happy face laugh cry" },
    { L"🙂", L"Slightly Smiling Face", L"smile happy face" },
    { L"🙃", L"Upside-Down Face", L"smile happy face upside down" },
    { L"😉", L"Winking Face", L"smile happy face wink" },
    { L"😊", L"Smiling Face with Smiling Eyes", L"smile happy face blush" },
    { L"😇", L"Smiling Face with Halo", L"smile happy face halo angel" },
    { L"🥰", L"Smiling Face with Hearts", L"smile happy face love heart" },
    { L"😍", L"Smiling Face with Heart-Eyes", L"smile happy face love heart" },
    { L"🤩", L"Star-Struck", L"smile happy face star" },
    { L"😘", L"Face Blowing a Kiss", L"smile happy face kiss love" },
    { L"😗", L"Kissing Face", L"smile happy face kiss" },
    { L"😚", L"Kissing Face with Closed Eyes", L"smile happy face kiss" },
    { L"😙", L"Kissing Face with Smiling Eyes", L"smile happy face kiss" },
    { L"😋", L"Face Savoring Food", L"smile happy face yum" },
    { L"😛", L"Face with Tongue", L"smile happy face tongue" },
    { L"😜", L"Winking Face with Tongue", L"smile happy face tongue wink" },
    { L"🤪", L"Zany Face", L"smile happy face tongue zany" },
    { L"😝", L"Squinting Face with Tongue", L"smile happy face tongue" },
    { L"🤑", L"Money-Mouth Face", L"smile happy face money" },
    { L"🤗", L"Hugging Face", L"smile happy face hug" },
    { L"🤭", L"Face with Hand Over Mouth", L"smile happy face oops" },
    { L"🤫", L"Shushing Face", L"smile happy face shush quiet" },
    { L"🤔", L"Thinking Face", L"face think" },
    { L"🤐", L"Zipper-Mouth Face", L"face zip quiet" },
    { L"🤨", L"Face with Raised Eyebrow", L"face eyebrow" },
    { L"😐", L"Neutral Face", L"face neutral" },
    { L"😑", L"Expressionless Face", L"face expressionless" },
    { L"😶", L"Face Without Mouth", L"face no mouth" },
    { L"😏", L"Smirking Face", L"face smirk" },
    { L"😒", L"Unamused Face", L"face unamused" },
    { L"🙄", L"Face with Rolling Eyes", L"face roll eyes" },
    { L"😬", L"Grimacing Face", L"face grimace" },
    { L"🤥", L"Lying Face", L"face lie pinocchio" },
    { L"😌", L"Relieved Face", L"face relieved" },
    { L"😔", L"Pensive Face", L"face pensive sad" },
    { L"😪", L"Sleepy Face", L"face sleepy" },
    { L"🤤", L"Drooling Face", L"face drool" },
    { L"😴", L"Sleeping Face", L"face sleep zzz" },
    { L"😷", L"Face with Medical Mask", L"face mask sick" },
    { L"🤒", L"Face with Thermometer", L"face thermometer sick" },
    { L"🤕", L"Face with Head-Bandage", L"face bandage sick" },
    { L"🤢", L"Nauseated Face", L"face nauseated sick" },
    { L"🤮", L"Face Vomiting", L"face vomit sick" },
    { L"🤧", L"Sneezing Face", L"face sneeze sick" },
    { L"🥵", L"Hot Face", L"face hot" },
    { L"🥶", L"Cold Face", L"face cold" },
    { L"🥴", L"Woozy Face", L"face woozy" },
    { L"😵", L"Dizzy Face", L"face dizzy" },
    { L"🤯", L"Exploding Head", L"face explode mind blown" },
    { L"🤠", L"Cowboy Hat Face", L"face cowboy" },
    { L"🥳", L"Partying Face", L"face party" },
    { L"😎", L"Smiling Face with Sunglasses", L"face cool sunglasses" },
    { L"🤓", L"Nerd Face", L"face nerd" },
    { L"🧐", L"Face with Monocle", L"face monocle" },
    { L"😕", L"Confused Face", L"face confused" },
    { L"😟", L"Worried Face", L"face worried" },
    { L"🙁", L"Slightly Frowning Face", L"face frown sad" },
    { L"☹️", L"Frowning Face", L"face frown sad" },
    { L"😮", L"Face with Open Mouth", L"face open mouth" },
    { L"😯", L"Hushed Face", L"face hushed" },
    { L"😲", L"Astonished Face", L"face astonished" },
    { L"😳", L"Flushed Face", L"face flushed" },
    { L"🥺", L"Pleading Face", L"face pleading" },
    { L"😦", L"Frowning Face with Open Mouth", L"face frown open mouth" },
    { L"😧", L"Anguished Face", L"face anguished" },
    { L"😨", L"Fearful Face", L"face fearful" },
    { L"😰", L"Anxious Face with Sweat", L"face anxious sweat" },
    { L"😥", L"Sad but Relieved Face", L"face sad relieved" },
    { L"😢", L"Crying Face", L"face cry sad" },
    { L"😭", L"Loudly Crying Face", L"face cry sad loud" },
    { L"😱", L"Face Screaming in Fear", L"face scream fear" },
    { L"😖", L"Confounded Face", L"face confounded" },
    { L"😣", L"Persevering Face", L"face persevering" },
    { L"😞", L"Disappointed Face", L"face disappointed" },
    { L"😓", L"Downcast Face with Sweat", L"face downcast sweat" },
    { L"😩", L"Weary Face", L"face weary" },
    { L"😫", L"Tired Face", L"face tired" },
    { L"🥱", L"Yawning Face", L"face yawn" },
    { L"😤", L"Face with Steam From Nose", L"face steam angry" },
    { L"😡", L"Pouting Face", L"face pout angry" },
    { L"😠", L"Angry Face", L"face angry" },
    { L"🤬", L"Face with Symbols on Mouth", L"face curse angry" },
    { L"😈", L"Smiling Face with Horns", L"face devil smile" },
    { L"👿", L"Angry Face with Horns", L"face devil angry" },
    { L"💀", L"Skull", L"skull death" },
    { L"☠️", L"Skull and Crossbones", L"skull death pirate" },
    { L"💩", L"Pile of Poo", L"poo poop" },
    { L"🤡", L"Clown Face", L"clown" },
    { L"👹", L"Ogre", L"ogre monster" },
    { L"👺", L"Goblin", L"goblin monster" },
    { L"👻", L"Ghost", L"ghost" },
    { L"👽", L"Alien", L"alien" },
    { L"👾", L"Alien Monster", L"alien monster game" },
    { L"🤖", L"Robot", L"robot" },
    { L"😺", L"Grinning Cat", L"cat smile" },
    { L"😸", L"Grinning Cat with Smiling Eyes", L"cat smile" },
    { L"😹", L"Cat with Tears of Joy", L"cat cry laugh" },
    { L"😻", L"Smiling Cat with Heart-Eyes", L"cat love heart" },
    { L"😼", L"Cat with Wry Smile", L"cat smile" },
    { L"😽", L"Kissing Cat", L"cat kiss" },
    { L"🙀", L"Weary Cat", L"cat weary" },
    { L"😿", L"Crying Cat", L"cat cry" },
    { L"😾", L"Pouting Cat", L"cat pout angry" },
    { L"💋", L"Kiss Mark", L"kiss lips" },
    { L"👋", L"Waving Hand", L"hand wave" },
    { L"🤚", L"Raised Back of Hand", L"hand raised" },
    { L"🖐️", L"Hand with Fingers Splayed", L"hand splayed" },
    { L"✋", L"Raised Hand", L"hand raised" },
    { L"🖖", L"Vulcan Salute", L"hand vulcan" },
    { L"👌", L"OK Hand", L"hand ok" },
    { L"🤏", L"Pinching Hand", L"hand pinch" },
    { L"✌️", L"Victory Hand", L"hand victory peace" },
    { L"🤞", L"Crossed Fingers", L"hand crossed luck" },
    { L"🤟", L"Love-You Gesture", L"hand love" },
    { L"🤘", L"Sign of the Horns", L"hand horns rock" },
    { L"🤙", L"Call Me Hand", L"hand call" },
    { L"👈", L"Backhand Index Pointing Left", L"hand point left" },
    { L"👉", L"Backhand Index Pointing Right", L"hand point right" },
    { L"👆", L"Backhand Index Pointing Up", L"hand point up" },
    { L"🖕", L"Middle Finger", L"hand middle finger" },
    { L"👇", L"Backhand Index Pointing Down", L"hand point down" },
    { L"☝️", L"Index Pointing Up", L"hand point up" },
    { L"👍", L"Thumbs Up", L"hand thumb up" },
    { L"👎", L"Thumbs Down", L"hand thumb down" },
    { L"✊", L"Raised Fist", L"hand fist" },
    { L"👊", L"Oncoming Fist", L"hand fist" },
    { L"🤛", L"Left-Facing Fist", L"hand fist left" },
    { L"🤜", L"Right-Facing Fist", L"hand fist right" },
    { L"👏", L"Clapping Hands", L"hand clap" },
    { L"🙌", L"Raising Hands", L"hand raise" },
    { L"👐", L"Open Hands", L"hand open" },
    { L"🤲", L"Palms Up Together", L"hand palms" },
    { L"🤝", L"Handshake", L"hand shake" },
    { L"🙏", L"Folded Hands", L"hand pray" },
    { L"✍️", L"Writing Hand", L"hand write" },
    { L"💅", L"Nail Polish", L"hand nail" },
    { L"🤳", L"Selfie", L"hand selfie" },
    { L"💪", L"Flexed Biceps", L"hand muscle" },
    { L"🦵", L"Leg", L"body leg" },
    { L"🦶", L"Foot", L"body foot" },
    { L"👂", L"Ear", L"body ear" },
    { L"🦻", L"Ear with Hearing Aid", L"body ear hearing aid" },
    { L"👃", L"Nose", L"body nose" },
    { L"🧠", L"Brain", L"body brain" },
    { L"🦷", L"Tooth", L"body tooth" },
    { L"🦴", L"Bone", L"body bone" },
    { L"👀", L"Eyes", L"body eyes" },
    { L"👁️", L"Eye", L"body eye" },
    { L"👅", L"Tongue", L"body tongue" },
    { L"👄", L"Mouth", L"body mouth" },
    { L"👶", L"Baby", L"person baby" },
    { L"🧒", L"Child", L"person child" },
    { L"👦", L"Boy", L"person boy" },
    { L"👧", L"Girl", L"person girl" },
    { L"🧑", L"Person", L"person" },
    { L"👱", L"Person: Blond Hair", L"person blond" },
    { L"👨", L"Man", L"person man" },
    { L"🧔", L"Person: Beard", L"person beard" },
    { L"👩", L"Woman", L"person woman" },
    { L"🧓", L"Older Person", L"person old" },
    { L"👴", L"Old Man", L"person old man" },
    { L"👵", L"Old Woman", L"person old woman" },
    { L"🙍", L"Person Frowning", L"person frown" },
    { L"🙎", L"Person Pouting", L"person pout" },
    { L"🙅", L"Person Gesturing No", L"person no" },
    { L"🙆", L"Person Gesturing OK", L"person ok" },
    { L"💁", L"Person Tipping Hand", L"person tip" },
    { L"🙋", L"Person Raising Hand", L"person raise" },
    { L"🙇", L"Person Bowing", L"person bow" },
    { L"🤦", L"Person Facepalming", L"person facepalm" },
    { L"🤷", L"Person Shrugging", L"person shrug" },
    { L"👮", L"Police Officer", L"person police" },
    { L"🕵️", L"Detective", L"person detective" },
    { L"💂", L"Guard", L"person guard" },
    { L"👷", L"Construction Worker", L"person construction" },
    { L"🤴", L"Prince", L"person prince" },
    { L"👸", L"Princess", L"person princess" },
    { L"👳", L"Person Wearing Turban", L"person turban" },
    { L"👲", L"Person With Skullcap", L"person skullcap" },
    { L"🧕", L"Woman with Headscarf", L"person headscarf" },
    { L"🤵", L"Person in Tuxedo", L"person tuxedo" },
    { L"👰", L"Person With Veil", L"person veil" },
    { L"🤰", L"Pregnant Woman", L"person pregnant" },
    { L"🤱", L"Breast-Feeding", L"person breastfeed" },
    { L"👼", L"Baby Angel", L"person angel" },
    { L"🎅", L"Santa Claus", L"person santa" },
    { L"🤶", L"Mrs. Claus", L"person mrs claus" },
    { L"🦸", L"Superhero", L"person superhero" },
    { L"🦹", L"Supervillain", L"person supervillain" },
    { L"🧙", L"Mage", L"person mage" },
    { L"🧚", L"Fairy", L"person fairy" },
    { L"🧛", L"Vampire", L"person vampire" },
    { L"🧜", L"Merperson", L"person mermaid" },
    { L"🧝", L"Elf", L"person elf" },
    { L"🧞", L"Genie", L"person genie" },
    { L"🧟", L"Zombie", L"person zombie" },
    { L"💆", L"Person Getting Massage", L"person massage" },
    { L"💇", L"Person Getting Haircut", L"person haircut" },
    { L"🚶", L"Person Walking", L"person walk" },
    { L"🏃", L"Person Running", L"person run" },
    { L"💃", L"Woman Dancing", L"person dance" },
    { L"🕺", L"Man Dancing", L"person dance" },
    { L"🕴️", L"Person in Suit Levitating", L"person levitate" },
    { L"👯", L"People with Bunny Ears", L"person bunny" },
    { L"🧖", L"Person in Steamy Room", L"person steam" },
    { L"🧗", L"Person Climbing", L"person climb" },
    { L"🧘", L"Person in Lotus Position", L"person yoga" },
    { L"🛀", L"Person Taking Bath", L"person bath" },
    { L"🛌", L"Person in Bed", L"person bed" },
    { L"🕴️", L"Person in Suit Levitating", L"person levitate" },
    { L"🗣️", L"Speaking Head", L"person speak" },
    { L"👤", L"Bust in Silhouette", L"person silhouette" },
    { L"👥", L"Busts in Silhouette", L"person silhouette" },
    { L"🤺", L"Person Fencing", L"person fence" },
    { L"🏇", L"Horse Racing", L"person horse" },
    { L"⛷️", L"Skier", L"person ski" },
    { L"🏂", L"Snowboarder", L"person snowboard" },
    { L"🏌️", L"Person Golfing", L"person golf" },
    { L"🏄", L"Person Surfing", L"person surf" },
    { L"🚣", L"Person Rowing Boat", L"person row" },
    { L"🏊", L"Person Swimming", L"person swim" },
    { L"⛹️", L"Person Bouncing Ball", L"person ball" },
    { L"🏋️", L"Person Lifting Weights", L"person weight" },
    { L"🚴", L"Person Biking", L"person bike" },
    { L"🚵", L"Person Mountain Biking", L"person bike" },
    { L"🤸", L"Person Cartwheeling", L"person cartwheel" },
    { L"🤼", L"People Wrestling", L"person wrestle" },
    { L"🤽", L"Person Playing Water Polo", L"person water polo" },
    { L"🤾", L"Person Playing Handball", L"person handball" },
    { L"🤹", L"Person Juggling", L"person juggle" },
    { L"❤️", L"Red Heart", L"heart love" },
    { L"🧡", L"Orange Heart", L"heart love" },
    { L"💛", L"Yellow Heart", L"heart love" },
    { L"💚", L"Green Heart", L"heart love" },
    { L"💙", L"Blue Heart", L"heart love" },
    { L"💜", L"Purple Heart", L"heart love" },
    { L"🖤", L"Black Heart", L"heart love" },
    { L"🤍", L"White Heart", L"heart love" },
    { L"🤎", L"Brown Heart", L"heart love" },
    { L"💔", L"Broken Heart", L"heart break" },
    { L"❣️", L"Heart Exclamation", L"heart" },
    { L"💕", L"Two Hearts", L"heart love" },
    { L"💞", L"Revolving Hearts", L"heart love" },
    { L"💓", L"Beating Heart", L"heart love" },
    { L"💗", L"Growing Heart", L"heart love" },
    { L"💖", L"Sparkling Heart", L"heart love" },
    { L"💘", L"Heart with Arrow", L"heart love" },
    { L"💝", L"Heart with Ribbon", L"heart love" },
    { L"💟", L"Heart Decoration", L"heart love" },
    { L"☮️", L"Peace Symbol", L"peace" },
    { L"✝️", L"Latin Cross", L"cross" },
    { L"☪️", L"Star and Crescent", L"star crescent" },
    { L"🕉️", L"Om", L"om" },
    { L"☸️", L"Wheel of Dharma", L"wheel" },
    { L"✡️", L"Star of David", L"star" },
    { L"🔯", L"Six Pointed Star", L"star" },
    { L"🕎", L"Menorah", L"menorah" },
    { L"☯️", L"Yin Yang", L"yin yang" },
    { L"☦️", L"Orthodox Cross", L"cross" },
    { L"🛐", L"Place of Worship", L"worship" },
    { L"⛎", L"Ophiuchus", L"zodiac" },
    { L"♈", L"Aries", L"zodiac" },
    { L"♉", L"Taurus", L"zodiac" },
    { L"♊", L"Gemini", L"zodiac" },
    { L"♋", L"Cancer", L"zodiac" },
    { L"♌", L"Leo", L"zodiac" },
    { L"♍", L"Virgo", L"zodiac" },
    { L"♎", L"Libra", L"zodiac" },
    { L"♏", L"Scorpio", L"zodiac" },
    { L"♐", L"Sagittarius", L"zodiac" },
    { L"♑", L"Capricorn", L"zodiac" },
    { L"♒", L"Aquarius", L"zodiac" },
    { L"♓", L"Pisces", L"zodiac" },
    { L"🆔", L"ID Button", L"id" },
    { L"⚛️", L"Atom Symbol", L"atom" },
    { L"🉑", L"Japanese Acceptable Button", L"japanese" },
    { L"☢️", L"Radioactive", L"radioactive" },
    { L"☣️", L"Biohazard", L"biohazard" },
    { L"📴", L"Mobile Phone Off", L"phone" },
    { L"📳", L"Vibration Mode", L"phone" },
    { L"🈶", L"Japanese Not Free of Charge Button", L"japanese" },
    { L"🈚", L"Japanese Free of Charge Button", L"japanese" },
    { L"🈸", L"Japanese Application Button", L"japanese" },
    { L"🈺", L"Japanese Open for Business Button", L"japanese" },
    { L"🈷️", L"Japanese Monthly Amount Button", L"japanese" },
    { L"✴️", L"Eight-Pointed Star", L"star" },
    { L"🆚", L"VS Button", L"vs" },
    { L"💮", L"White Flower", L"flower" },
    { L"🉐", L"Japanese Bargain Button", L"japanese" },
    { L"㊙️", L"Japanese Secret Button", L"japanese" },
    { L"㊗️", L"Japanese Congratulations Button", L"japanese" },
    { L"🈴", L"Japanese Passing Grade Button", L"japanese" },
    { L"🈵", L"Japanese No Vacancy Button", L"japanese" },
    { L"🈹", L"Japanese Discount Button", L"japanese" },
    { L"🈲", L"Japanese Prohibited Button", L"japanese" },
    { L"🅰️", L"A Button (Blood Type)", L"blood" },
    { L"🅱️", L"B Button (Blood Type)", L"blood" },
    { L"🆎", L"AB Button (Blood Type)", L"blood" },
    { L"🆑", L"CL Button", L"cl" },
    { L"🅾️", L"O Button (Blood Type)", L"blood" },
    { L"🆘", L"SOS Button", L"sos" },
    { L"❌", L"Cross Mark", L"cross" },
    { L"⭕", L"Hollow Red Circle", L"circle" },
    { L"🛑", L"Stop Sign", L"stop" },
    { L"⛔", L"No Entry", L"no entry" },
    { L"📛", L"Name Badge", L"name" },
    { L"🚫", L"Prohibited", L"prohibited" },
    { L"💯", L"Hundred Points", L"100" },
    { L"💢", L"Anger Symbol", L"anger" },
    { L"♨️", L"Hot Springs", L"hot" },
    { L"🚷", L"No Pedestrians", L"no" },
    { L"🚯", L"No Littering", L"no" },
    { L"🚳", L"No Bicycles", L"no" },
    { L"🚱", L"Non-Potable Water", L"no" },
    { L"🔞", L"No One Under Eighteen", L"no" },
    { L"📵", L"No Mobile Phones", L"no" },
    { L"🚭", L"No Smoking", L"no" },
    { L"❗", L"Exclamation Mark", L"exclamation" },
    { L"❕", L"White Exclamation Mark", L"exclamation" },
    { L"❓", L"Question Mark", L"question" },
    { L"❔", L"White Question Mark", L"question" },
    { L"‼️", L"Double Exclamation Mark", L"exclamation" },
    { L"⁉️", L"Exclamation Question Mark", L"exclamation question" },
    { L"🔅", L"Dim Button", L"dim" },
    { L"🔆", L"Bright Button", L"bright" },
    { L"〽️", L"Part Alternation Mark", L"mark" },
    { L"⚠️", L"Warning", L"warning" },
    { L"🚸", L"Children Crossing", L"children" },
    { L"🔱", L"Trident Emblem", L"trident" },
    { L"⚜️", L"Fleur-de-lis", L"fleur" },
    { L"🔰", L"Japanese Symbol for Beginner", L"japanese" },
    { L"♻️", L"Recycling Symbol", L"recycle" },
    { L"✅", L"Check Mark Button", L"check" },
    { L"🈯", L"Japanese Reserved Button", L"japanese" },
    { L"💹", L"Chart Increasing with Yen", L"chart" },
    { L"❇️", L"Sparkle", L"sparkle" },
    { L"✳️", L"Eight-Spoked Asterisk", L"asterisk" },
    { L"❎", L"Cross Mark Button", L"cross" },
    { L"🌐", L"Globe with Meridians", L"globe" },
    { L"💠", L"Diamond with a Dot", L"diamond" },
    { L"Ⓜ️", L"Circled M", L"m" },
    { L"🌀", L"Cyclone", L"cyclone" },
    { L"💤", L"Zzz", L"sleep" },
    { L"🏧", L"ATM Sign", L"atm" },
    { L"🚾", L"Water Closet", L"wc" },
    { L"♿", L"Wheelchair Symbol", L"wheelchair" },
    { L"🅿️", L"P Button", L"p" },
    { L"🈳", L"Japanese Vacancy Button", L"japanese" },
    { L"🈂️", L"Japanese Service Charge Button", L"japanese" },
    { L"🛂", L"Passport Control", L"passport" },
    { L"🛃", L"Customs", L"customs" },
    { L"🛄", L"Baggage Claim", L"baggage" },
    { L"🛅", L"Left Luggage", L"luggage" },
    { L"🚀", L"Rocket", L"rocket space" },
    { L"🚁", L"Helicopter", L"helicopter" },
    { L"🚂", L"Locomotive", L"train" },
    { L"🚃", L"Railway Car", L"train" },
    { L"🚄", L"High-Speed Train", L"train" },
    { L"🚅", L"Bullet Train", L"train" },
    { L"🚆", L"Train", L"train" },
    { L"🚇", L"Metro", L"train" },
    { L"🚈", L"Light Rail", L"train" },
    { L"🚉", L"Station", L"station" },
    { L"🚊", L"Tram", L"tram" },
    { L"🚝", L"Monorail", L"monorail" },
    { L"🚞", L"Mountain Railway", L"train" },
    { L"🚋", L"Tram Car", L"tram" },
    { L"🚌", L"Bus", L"bus" },
    { L"🚍", L"Oncoming Bus", L"bus" },
    { L"🚎", L"Trolleybus", L"bus" },
    { L"🚐", L"Minibus", L"bus" },
    { L"🚑", L"Ambulance", L"ambulance" },
    { L"🚒", L"Fire Engine", L"fire" },
    { L"🚓", L"Police Car", L"police" },
    { L"🚔", L"Oncoming Police Car", L"police" },
    { L"🚕", L"Taxi", L"taxi" },
    { L"🚖", L"Oncoming Taxi", L"taxi" },
    { L"🚗", L"Automobile", L"car" },
    { L"🚘", L"Oncoming Automobile", L"car" },
    { L"🚙", L"Sport Utility Vehicle", L"car" },
    { L"🚚", L"Delivery Truck", L"truck" },
    { L"🚛", L"Articulated Lorry", L"truck" },
    { L"🚜", L"Tractor", L"tractor" },
    { L"🏎️", L"Racing Car", L"car" },
    { L"🏍️", L"Motorcycle", L"motorcycle" },
    { L"🛵", L"Motor Scooter", L"scooter" },
    { L"🦽", L"Manual Wheelchair", L"wheelchair" },
    { L"🦼", L"Motorized Wheelchair", L"wheelchair" },
    { L"🛺", L"Auto Rickshaw", L"rickshaw" },
    { L"🚲", L"Bicycle", L"bike" },
    { L"🛴", L"Kick Scooter", L"scooter" },
    { L"🛹", L"Skateboard", L"skateboard" },
    { L"🚏", L"Bus Stop", L"bus" },
    { L"🛣️", L"Motorway", L"road" },
    { L"🛤️", L"Railway Track", L"train" },
    { L"🛢️", L"Oil Drum", L"oil" },
    { L"⛽", L"Fuel Pump", L"fuel" },
    { L"🚨", L"Police Car Light", L"police" },
    { L"🚥", L"Horizontal Traffic Light", L"light" },
    { L"🚦", L"Vertical Traffic Light", L"light" },
    { L"🛑", L"Stop Sign", L"stop" },
    { L"🚧", L"Construction", L"construction" },
    { L"⚓", L"Anchor", L"anchor" },
    { L"⛵", L"Sailboat", L"boat" },
    { L"🛶", L"Canoe", L"boat" },
    { L"🚤", L"Speedboat", L"boat" },
    { L"🛳️", L"Passenger Ship", L"ship" },
    { L"⛴️", L"Ferry", L"ferry" },
    { L"🛥️", L"Motor Boat", L"boat" },
    { L"🚢", L"Ship", L"ship" },
    { L"✈️", L"Airplane", L"plane" },
    { L"🛩️", L"Small Airplane", L"plane" },
    { L"🛫", L"Airplane Departure", L"plane" },
    { L"🛬", L"Airplane Arrival", L"plane" },
    { L"🪂", L"Parachute", L"parachute" },
    { L"💺", L"Seat", L"seat" },
    { L"🚁", L"Helicopter", L"helicopter" },
    { L"🚟", L"Suspension Railway", L"train" },
    { L"🚠", L"Mountain Cableway", L"cable" },
    { L"🚡", L"Aerial Tramway", L"tram" },
    { L"🛰️", L"Satellite", L"satellite" },
    { L"🚀", L"Rocket", L"rocket" },
    { L"🛸", L"Flying Saucer", L"ufo" },
    { L"🛎️", L"Bellhop Bell", L"bell" },
    { L"🧳", L"Luggage", L"luggage" },
    { L"⌛", L"Hourglass Done", L"time" },
    { L"⏳", L"Hourglass Not Done", L"time" },
    { L"⌚", L"Watch", L"watch" },
    { L"⏰", L"Alarm Clock", L"clock" },
    { L"⏱️", L"Stopwatch", L"stopwatch" },
    { L"⏲️", L"Timer Clock", L"timer" },
    { L"🕰️", L"Mantelpiece Clock", L"clock" },
    { L"🕛", L"Twelve O’Clock", L"clock" },
    { L"🕧", L"Twelve-Thirty", L"clock" },
    { L"🕐", L"One O’Clock", L"clock" },
    { L"🕜", L"One-Thirty", L"clock" },
    { L"🕑", L"Two O’Clock", L"clock" },
    { L"🕝", L"Two-Thirty", L"clock" },
    { L"🕒", L"Three O’Clock", L"clock" },
    { L"🕞", L"Three-Thirty", L"clock" },
    { L"🕓", L"Four O’Clock", L"clock" },
    { L"🕟", L"Four-Thirty", L"clock" },
    { L"🕔", L"Five O’Clock", L"clock" },
    { L"🕠", L"Five-Thirty", L"clock" },
    { L"🕕", L"Six O’Clock", L"clock" },
    { L"🕡", L"Six-Thirty", L"clock" },
    { L"🕖", L"Seven O’Clock", L"clock" },
    { L"🕢", L"Seven-Thirty", L"clock" },
    { L"🕗", L"Eight O’Clock", L"clock" },
    { L"🕣", L"Eight-Thirty", L"clock" },
    { L"🕘", L"Nine O’Clock", L"clock" },
    { L"🕤", L"Nine-Thirty", L"clock" },
    { L"🕙", L"Ten O’Clock", L"clock" },
    { L"🕥", L"Ten-Thirty", L"clock" },
    { L"🕚", L"Eleven O’Clock", L"clock" },
    { L"🕦", L"Eleven-Thirty", L"clock" },
    { L"🌑", L"New Moon", L"moon" },
    { L"🌒", L"Waxing Crescent Moon", L"moon" },
    { L"🌓", L"First Quarter Moon", L"moon" },
    { L"🌔", L"Waxing Gibbous Moon", L"moon" },
    { L"🌕", L"Full Moon", L"moon" },
    { L"🌖", L"Waning Gibbous Moon", L"moon" },
    { L"🌗", L"Last Quarter Moon", L"moon" },
    { L"🌘", L"Waning Crescent Moon", L"moon" },
    { L"🌙", L"Crescent Moon", L"moon" },
    { L"🌚", L"New Moon Face", L"moon" },
    { L"🌛", L"First Quarter Moon Face", L"moon" },
    { L"🌜", L"Last Quarter Moon Face", L"moon" },
    { L"☀️", L"Sun", L"sun" },
    { L"🌝", L"Full Moon Face", L"moon" },
    { L"🌞", L"Sun with Face", L"sun" },
    { L"⭐", L"Star", L"star" },
    { L"🌟", L"Glowing Star", L"star" },
    { L"🌠", L"Shooting Star", L"star" },
    { L"☁️", L"Cloud", L"cloud" },
    { L"⛅", L"Sun Behind Cloud", L"cloud" },
    { L"⛈️", L"Cloud with Lightning and Rain", L"cloud" },
    { L"🌤️", L"Sun Behind Small Cloud", L"cloud" },
    { L"🌥️", L"Sun Behind Large Cloud", L"cloud" },
    { L"🌦️", L"Sun Behind Rain Cloud", L"cloud" },
    { L"🌧️", L"Cloud with Rain", L"cloud" },
    { L"🌨️", L"Cloud with Snow", L"cloud" },
    { L"🌩️", L"Cloud with Lightning", L"cloud" },
    { L"🌪️", L"Tornado", L"tornado" },
    { L"🌫️", L"Fog", L"fog" },
    { L"🌬️", L"Wind Face", L"wind" },
    { L"🌈", L"Rainbow", L"rainbow" },
    { L"☂️", L"Umbrella", L"umbrella" },
    { L"☔", L"Umbrella with Rain Drops", L"umbrella" },
    { L"⚡", L"High Voltage", L"voltage" },
    { L"❄️", L"Snowflake", L"snow" },
    { L"☃️", L"Snowman", L"snowman" },
    { L"⛄", L"Snowman Without Snow", L"snowman" },
    { L"☄️", L"Comet", L"comet" },
    { L"🔥", L"Fire", L"fire" },
    { L"💧", L"Droplet", L"water" },
    { L"🌊", L"Water Wave", L"water" },
    { L"🎃", L"Jack-O-Lantern", L"halloween" },
    { L"🎄", L"Christmas Tree", L"christmas" },
    { L"🎆", L"Fireworks", L"fireworks" },
    { L"🎇", L"Sparkler", L"sparkler" },
    { L"🧨", L"Firecracker", L"firecracker" },
    { L"✨", L"Sparkles", L"sparkles" },
    { L"🎈", L"Balloon", L"balloon" },
    { L"🎉", L"Party Popper", L"party" },
    { L"🎊", L"Confetti Ball", L"confetti" },
    { L"🎋", L"Tanabata Tree", L"tree" },
    { L"🎍", L"Pine Decoration", L"decoration" },
    { L"🎎", L"Japanese Dolls", L"dolls" },
    { L"🎏", L"Carp Streamer", L"carp" },
    { L"🎐", L"Wind Chime", L"chime" },
    { L"🎑", L"Moon Viewing Ceremony", L"moon" },
    { L"🧧", L"Red Envelope", L"envelope" },
    { L"🎀", L"Ribbon", L"ribbon" },
    { L"🎁", L"Wrapped Gift", L"gift" },
    { L"🎗️", L"Reminder Ribbon", L"ribbon" },
    { L"🎟️", L"Admission Tickets", L"ticket" },
    { L"🎫", L"Ticket", L"ticket" },
    { L"🎖️", L"Military Medal", L"medal" },
    { L"🏆", L"Trophy", L"trophy" },
    { L"🏅", L"Sports Medal", L"medal" },
    { L"🥇", L"1st Place Medal", L"medal" },
    { L"🥈", L"2nd Place Medal", L"medal" },
    { L"🥉", L"3rd Place Medal", L"medal" },
    { L"⚽", L"Soccer Ball", L"ball" },
    { L"⚾", L"Baseball", L"ball" },
    { L"🥎", L"Softball", L"ball" },
    { L"🏀", L"Basketball", L"ball" },
    { L"🏐", L"Volleyball", L"ball" },
    { L"🏈", L"American Football", L"ball" },
    { L"🏉", L"Rugby Football", L"ball" },
    { L"🎾", L"Tennis", L"ball" },
    { L"🥏", L"Flying Disc", L"disc" },
    { L"🎳", L"Bowling", L"bowling" },
    { L"🏏", L"Cricket Game", L"cricket" },
    { L"🏑", L"Field Hockey", L"hockey" },
    { L"🏒", L"Ice Hockey", L"hockey" },
    { L"🥍", L"Lacrosse", L"lacrosse" },
    { L"🏓", L"Ping Pong", L"ping pong" },
    { L"🏸", L"Badminton", L"badminton" },
    { L"🥊", L"Boxing Glove", L"boxing" },
    { L"🥋", L"Martial Arts Uniform", L"martial arts" },
    { L"🥅", L"Goal Net", L"goal" },
    { L"⛳", L"Flag in Hole", L"golf" },
    { L"⛸️", L"Ice Skate", L"skate" },
    { L"🎣", L"Fishing Pole", L"fishing" },
    { L"🤿", L"Diving Mask", L"diving" },
    { L"🎽", L"Running Shirt", L"shirt" },
    { L"🎿", L"Skis", L"ski" },
    { L"🛷", L"Sled", L"sled" },
    { L"🥌", L"Curling Stone", L"curling" },
    { L"🎯", L"Bullseye", L"target" },
    { L"🪀", L"Yo-Yo", L"toy" },
    { L"🪁", L"Kite", L"kite" },
    { L"🎱", L"Pool 8 Ball", L"ball" },
    { L"🔮", L"Crystal Ball", L"ball" },
    { L"🧿", L"Nazar Amulet", L"amulet" },
    { L"🎮", L"Video Game", L"game" },
    { L"🕹️", L"Joystick", L"game" },
    { L"🎰", L"Slot Machine", L"game" },
    { L"🎲", L"Game Die", L"game" },
    { L"🧩", L"Puzzle Piece", L"puzzle" },
    { L"🧸", L"Teddy Bear", L"toy" },
    { L"♠️", L"Spade Suit", L"card" },
    { L"♥️", L"Heart Suit", L"card" },
    { L"♦️", L"Diamond Suit", L"card" },
    { L"♣️", L"Club Suit", L"card" },
    { L"♟️", L"Chess Pawn", L"chess" },
    { L"🃏", L"Joker", L"card" },
    { L"🀄", L"Mahjong Red Dragon", L"mahjong" },
    { L"🎴", L"Flower Playing Cards", L"card" },
    { L"🎭", L"Performing Arts", L"art" },
    { L"🖼️", L"Framed Picture", L"picture" },
    { L"🎨", L"Artist Palette", L"art" },
    { L"🧵", L"Thread", L"thread" },
    { L"🧶", L"Yarn", L"yarn" },
    { L"👓", L"Glasses", L"glasses" },
    { L"🕶️", L"Sunglasses", L"sunglasses" },
    { L"🥽", L"Goggles", L"goggles" },
    { L"🥼", L"Lab Coat", L"coat" },
    { L"🦺", L"Safety Vest", L"vest" },
    { L"👔", L"Necktie", L"tie" },
    { L"👕", L"T-Shirt", L"shirt" },
    { L"👖", L"Jeans", L"pants" },
    { L"🧣", L"Scarf", L"scarf" },
    { L"🧤", L"Gloves", L"gloves" },
    { L"🧥", L"Coat", L"coat" },
    { L"🧦", L"Socks", L"socks" },
    { L"👗", L"Dress", L"dress" },
    { L"👘", L"Kimono", L"kimono" },
    { L"🥻", L"Sari", L"sari" },
    { L"🩱", L"One-Piece Swimsuit", L"swimsuit" },
    { L"🩲", L"Briefs", L"underwear" },
    { L"🩳", L"Shorts", L"shorts" },
    { L"👙", L"Bikini", L"bikini" },
    { L"👚", L"Woman’s Clothes", L"clothes" },
    { L"👛", L"Purse", L"purse" },
    { L"👜", L"Handbag", L"bag" },
    { L"👝", L"Clutch Bag", L"bag" },
    { L"🛍️", L"Shopping Bags", L"bag" },
    { L"🎒", L"Backpack", L"bag" },
    { L"👞", L"Man’s Shoe", L"shoe" },
    { L"👟", L"Running Shoe", L"shoe" },
    { L"🥾", L"Hiking Boot", L"boot" },
    { L"🥿", L"Flat Shoe", L"shoe" },
    { L"👠", L"High-Heeled Shoe", L"shoe" },
    { L"👡", L"Woman’s Sandal", L"shoe" },
    { L"🩰", L"Ballet Shoes", L"shoe" },
    { L"👢", L"Woman’s Boot", L"boot" },
    { L"👑", L"Crown", L"crown" },
    { L"👒", L"Woman’s Hat", L"hat" },
    { L"🎩", L"Top Hat", L"hat" },
    { L"🎓", L"Graduation Cap", L"hat" },
    { L"🧢", L"Billed Cap", L"hat" },
    { L"⛑️", L"Rescue Worker’s Helmet", L"helmet" },
    { L"📿", L"Prayer Beads", L"beads" },
    { L"💄", L"Lipstick", L"lipstick" },
    { L"💍", L"Ring", L"ring" },
    { L"💎", L"Gem Stone", L"gem" },
    { L"🔇", L"Muted Speaker", L"sound" },
    { L"🔈", L"Speaker Low Volume", L"sound" },
    { L"🔉", L"Speaker Medium Volume", L"sound" },
    { L"🔊", L"Speaker High Volume", L"sound" },
    { L"📢", L"Loudspeaker", L"sound" },
    { L"📣", L"Megaphone", L"sound" },
    { L"📯", L"Postal Horn", L"sound" },
    { L"🔔", L"Bell", L"bell" },
    { L"🔕", L"Bell with Slash", L"bell" },
    { L"🎼", L"Musical Score", L"music" },
    { L"🎵", L"Musical Note", L"music" },
    { L"🎶", L"Musical Notes", L"music" },
    { L"🎙️", L"Studio Microphone", L"music" },
    { L"🎚️", L"Level Slider", L"music" },
    { L"🎛️", L"Control Knobs", L"music" },
    { L"🎤", L"Microphone", L"music" },
    { L"🎧", L"Headphone", L"music" },
    { L"📻", L"Radio", L"music" },
    { L"🎷", L"Saxophone", L"music" },
    { L"🎸", L"Guitar", L"music" },
    { L"🎹", L"Musical Keyboard", L"music" },
    { L"🎺", L"Trumpet", L"music" },
    { L"🎻", L"Violin", L"music" },
    { L"🪕", L"Banjo", L"music" },
    { L"🥁", L"Drum", L"music" },
    { L"📱", L"Mobile Phone", L"phone" },
    { L"📲", L"Mobile Phone with Arrow", L"phone" },
    { L"☎️", L"Telephone", L"phone" },
    { L"📞", L"Telephone Receiver", L"phone" },
    { L"📟", L"Pager", L"pager" },
    { L"📠", L"Fax Machine", L"fax" },
    { L"🔋", L"Battery", L"battery" },
    { L"🔌", L"Electric Plug", L"plug" },
    { L"💻", L"Laptop", L"computer" },
    { L"🖥️", L"Desktop Computer", L"computer" },
    { L"🖨️", L"Printer", L"printer" },
    { L"⌨️", L"Keyboard", L"keyboard" },
    { L"🖱️", L"Computer Mouse", L"mouse" },
    { L"🖲️", L"Trackball", L"mouse" },
    { L"💽", L"Computer Disk", L"disk" },
    { L"💾", L"Floppy Disk", L"disk" },
    { L"💿", L"Optical Disk", L"disk" },
    { L"📀", L"DVD", L"disk" },
    { L"🧮", L"Abacus", L"abacus" },
    { L"🎥", L"Movie Camera", L"camera" },
    { L"🎞️", L"Film Frames", L"film" },
    { L"📽️", L"Film Projector", L"projector" },
    { L"🎬", L"Clapper Board", L"movie" },
    { L"📺", L"Television", L"tv" },
    { L"📷", L"Camera", L"camera" },
    { L"📸", L"Camera with Flash", L"camera" },
    { L"📹", L"Video Camera", L"camera" },
    { L"📼", L"Videocassette", L"video" },
    { L"🔍", L"Magnifying Glass Tilted Left", L"search" },
    { L"🔎", L"Magnifying Glass Tilted Right", L"search" },
    { L"🕯️", L"Candle", L"candle" },
    { L"💡", L"Light Bulb", L"light" },
    { L"🔦", L"Flashlight", L"light" },
    { L"🏮", L"Red Paper Lantern", L"lantern" },
    { L"🪔", L"Diya Lamp", L"lamp" },
    { L"📔", L"Notebook with Decorative Cover", L"book" },
    { L"📕", L"Closed Book", L"book" },
    { L"📖", L"Open Book", L"book" },
    { L"📗", L"Green Book", L"book" },
    { L"📘", L"Blue Book", L"book" },
    { L"📙", L"Orange Book", L"book" },
    { L"📚", L"Books", L"book" },
    { L"📓", L"Notebook", L"book" },
    { L"📒", L"Ledger", L"book" },
    { L"📃", L"Page with Curl", L"page" },
    { L"📜", L"Scroll", L"scroll" },
    { L"📄", L"Page Facing Up", L"page" },
    { L"📰", L"Newspaper", L"news" },
    { L"🗞️", L"Rolled-Up Newspaper", L"news" },
    { L"📑", L"Bookmark Tabs", L"tab" },
    { L"🔖", L"Bookmark", L"bookmark" },
    { L"🏷️", L"Label", L"label" },
    { L"💰", L"Money Bag", L"money" },
    { L"💴", L"Yen Banknote", L"money" },
    { L"💵", L"Dollar Banknote", L"money" },
    { L"💶", L"Euro Banknote", L"money" },
    { L"💷", L"Pound Banknote", L"money" },
    { L"💸", L"Money with Wings", L"money" },
    { L"💳", L"Credit Card", L"money" },
    { L"🧾", L"Receipt", L"receipt" },
    { L"💹", L"Chart Increasing with Yen", L"chart" },
    { L"💱", L"Currency Exchange", L"exchange" },
    { L"💲", L"Heavy Dollar Sign", L"money" },
    { L"✉️", L"Envelope", L"email" },
    { L"📧", L"E-Mail", L"email" },
    { L"📨", L"Incoming Envelope", L"email" },
    { L"📩", L"Envelope with Arrow", L"email" },
    { L"📤", L"Outbox Tray", L"email" },
    { L"📥", L"Inbox Tray", L"email" },
    { L"📦", L"Package", L"package" },
    { L"📫", L"Closed Mailbox with Raised Flag", L"mail" },
    { L"📪", L"Closed Mailbox with Lowered Flag", L"mail" },
    { L"📬", L"Open Mailbox with Raised Flag", L"mail" },
    { L"📭", L"Open Mailbox with Lowered Flag", L"mail" },
    { L"📮", L"Postbox", L"mail" },
    { L"🗳️", L"Ballot Box with Ballot", L"vote" },
    { L"✏️", L"Pencil", L"pencil" },
    { L"✒️", L"Black Nib", L"pen" },
    { L"🖋️", L"Fountain Pen", L"pen" },
    { L"🖊️", L"Pen", L"pen" },
    { L"🖌️", L"Paintbrush", L"brush" },
    { L"🖍️", L"Crayon", L"crayon" },
    { L"📝", L"Memo", L"memo" },
    { L"💼", L"Briefcase", L"briefcase" },
    { L"📁", L"File Folder", L"folder" },
    { L"📂", L"Open File Folder", L"folder" },
    { L"🗂️", L"Card Index Dividers", L"index" },
    { L"📅", L"Calendar", L"calendar" },
    { L"📆", L"Tear-Off Calendar", L"calendar" },
    { L"🗒️", L"Spiral Notepad", L"note" },
    { L"🗓️", L"Spiral Calendar", L"calendar" },
    { L"📇", L"Card Index", L"index" },
    { L"📈", L"Chart Increasing", L"chart" },
    { L"📉", L"Chart Decreasing", L"chart" },
    { L"📊", L"Bar Chart", L"chart" },
    { L"📋", L"Clipboard", L"clipboard" },
    { L"📌", L"Pushpin", L"pin" },
    { L"📍", L"Round Pushpin", L"pin" },
    { L"📎", L"Paperclip", L"clip" },
    { L"🖇️", L"Linked Paperclips", L"clip" },
    { L"📏", L"Straight Ruler", L"ruler" },
    { L"📐", L"Triangular Ruler", L"ruler" },
    { L"✂️", L"Scissors", L"scissors" },
    { L"🗃️", L"Card File Box", L"box" },
    { L"🗄️", L"File Cabinet", L"cabinet" },
    { L"🗑️", L"Wastebasket", L"trash" },
    { L"🔒", L"Locked", L"lock" },
    { L"🔓", L"Unlocked", L"lock" },
    { L"🔏", L"Locked with Pen", L"lock" },
    { L"🔐", L"Locked with Key", L"lock" },
    { L"🔑", L"Key", L"key" },
    { L"🗝️", L"Old Key", L"key" },
    { L"🔨", L"Hammer", L"tool" },
    { L"🪓", L"Axe", L"tool" },
    { L"⛏️", L"Pick", L"tool" },
    { L"⚒️", L"Hammer and Pick", L"tool" },
    { L"🛠️", L"Hammer and Wrench", L"tool" },
    { L"🗡️", L"Dagger", L"weapon" },
    { L"⚔️", L"Crossed Swords", L"weapon" },
    { L"🔫", L"Pistol", L"weapon" },
    { L"🏹", L"Bow and Arrow", L"weapon" },
    { L"🛡️", L"Shield", L"shield" },
    { L"🔧", L"Wrench", L"tool" },
    { L"🔩", L"Nut and Bolt", L"tool" },
    { L"⚙️", L"Gear", L"gear" },
    { L"🗜️", L"Clamp", L"tool" },
    { L"⚖️", L"Balance Scale", L"scale" },
    { L"🦯", L"White Cane", L"cane" },
    { L"🔗", L"Link", L"link" },
    { L"⛓️", L"Chains", L"chain" },
    { L"🧰", L"Toolbox", L"tool" },
    { L"🧲", L"Magnet", L"magnet" },
    { L"⚗️", L"Alembic", L"science" },
    { L"🧪", L"Test Tube", L"science" },
    { L"🧫", L"Petri Dish", L"science" },
    { L"🧬", L"DNA", L"science" },
    { L"🔬", L"Microscope", L"science" },
    { L"🔭", L"Telescope", L"science" },
    { L"📡", L"Satellite Antenna", L"antenna" },
    { L"💉", L"Syringe", L"medical" },
    { L"🩸", L"Drop of Blood", L"medical" },
    { L"💊", L"Pill", L"medical" },
    { L"🩹", L"Adhesive Bandage", L"medical" },
    { L"🩺", L"Stethoscope", L"medical" },
    { L"🚪", L"Door", L"door" },
    { L"🛏️", L"Bed", L"bed" },
    { L"🛋️", L"Couch and Lamp", L"couch" },
    { L"🪑", L"Chair", L"chair" },
    { L"🚽", L"Toilet", L"toilet" },
    { L"🚿", L"Shower", L"shower" },
    { L"🛁", L"Bathtub", L"bath" },
    { L"🪒", L"Razor", L"razor" },
    { L"🧴", L"Lotion Bottle", L"lotion" },
    { L"🧷", L"Safety Pin", L"pin" },
    { L"🧹", L"Broom", L"broom" },
    { L"🧺", L"Basket", L"basket" },
    { L"🧻", L"Roll of Paper", L"paper" },
    { L"🧼", L"Soap", L"soap" },
    { L"🧽", L"Sponge", L"sponge" },
    { L"🧯", L"Fire Extinguisher", L"fire" },
    { L"🛒", L"Shopping Cart", L"cart" },
    { L"🚬", L"Cigarette", L"smoke" },
    { L"⚰️", L"Coffin", L"coffin" },
    { L"⚱️", L"Funeral Urn", L"urn" },
    { L"🗿", L"Moai", L"moai" }
};

extern "C" {
    PLUGIN_API const wchar_t* GetPluginName() {
        return L"Emoji Picker";
    }
    
    PLUGIN_API const wchar_t* GetPluginDescription() {
        return L"Inserts common emojis.";
    }
    
    PLUGIN_API const wchar_t* GetPluginVersion() {
        return L"1.1";
    }

    std::vector<EmojiData> g_FilteredEmojis;

    void UpdateEmojiList(HWND hDlg) {
        HWND hList = GetDlgItem(hDlg, IDC_EMOJI_LIST);
        SendMessage(hList, LB_RESETCONTENT, 0, 0);
        
        TCHAR szSearch[256];
        GetDlgItemText(hDlg, IDC_EMOJI_SEARCH, szSearch, 256);
        std::wstring search = szSearch;
        std::transform(search.begin(), search.end(), search.begin(), ::towlower);
        
        g_FilteredEmojis.clear();
        
        for (const auto& item : g_EmojiList) {
            std::wstring name = item.name;
            std::wstring keywords = item.keywords;
            std::wstring full = name + L" " + keywords;
            std::transform(full.begin(), full.end(), full.begin(), ::towlower);
            
            if (search.empty() || full.find(search) != std::wstring::npos) {
                g_FilteredEmojis.push_back(item);
                std::wstring display = std::wstring(item.emoji) + L" - " + item.name;
                SendMessage(hList, LB_ADDSTRING, 0, (LPARAM)display.c_str());
            }
        }
    }

    INT_PTR CALLBACK EmojiDlgProc(HWND hDlg, UINT message, WPARAM wParam, LPARAM lParam) {
        switch (message) {
        case WM_INITDIALOG:
            UpdateEmojiList(hDlg);
            SetFocus(GetDlgItem(hDlg, IDC_EMOJI_SEARCH));
            return FALSE;
            
        case WM_COMMAND:
            if (LOWORD(wParam) == IDC_EMOJI_SEARCH && HIWORD(wParam) == EN_CHANGE) {
                UpdateEmojiList(hDlg);
            }
            else if (LOWORD(wParam) == IDC_EMOJI_LIST && HIWORD(wParam) == LBN_DBLCLK) {
                SendMessage(hDlg, WM_COMMAND, IDOK, 0);
            }
            else if (LOWORD(wParam) == IDOK) {
                HWND hList = GetDlgItem(hDlg, IDC_EMOJI_LIST);
                int sel = (int)SendMessage(hList, LB_GETCURSEL, 0, 0);
                if (sel != LB_ERR && sel < (int)g_FilteredEmojis.size()) {
                    EndDialog(hDlg, (INT_PTR)g_FilteredEmojis[sel].emoji);
                } else {
                    EndDialog(hDlg, 0);
                }
                return TRUE;
            }
            else if (LOWORD(wParam) == IDCANCEL) {
                EndDialog(hDlg, 0);
                return TRUE;
            }
            break;
        }
        return FALSE;
    }

    void OpenEmojiPicker(HWND hEditorWnd) {
        INT_PTR result = DialogBox(g_hInst, MAKEINTRESOURCE(IDD_EMOJI_PICKER), hEditorWnd, EmojiDlgProc);
        if (result != 0) {
            const wchar_t* emoji = (const wchar_t*)result;
            SendMessage(hEditorWnd, EM_REPLACESEL, TRUE, (LPARAM)emoji);
        }
    }

    PluginMenuItem g_Items[] = {
        { L"Open Emoji Picker...", OpenEmojiPicker }
    };

    PLUGIN_API PluginMenuItem* GetPluginMenuItems(int* count) {
        *count = sizeof(g_Items) / sizeof(PluginMenuItem);
        return g_Items;
    }
}

BOOL APIENTRY DllMain( HMODULE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
                     )
{
    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:
        g_hInst = hModule;
        break;
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}
